/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'image_url' : IDL.Text,
  'product_name' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Text;
export const Timestamp = IDL.Int;
export const StoreId = IDL.Text;
export const Product = IDL.Record({
  'product_id' : ProductId,
  'image_url' : IDL.Text,
  'created_at' : Timestamp,
  'product_name' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'store_id' : StoreId,
  'in_stock' : IDL.Bool,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DateKey = IDL.Text;
export const AnalyticsId = IDL.Text;
export const Analytics = IDL.Record({
  'whatsapp_clicks' : IDL.Nat,
  'click_count' : IDL.Nat,
  'date' : DateKey,
  'analytics_id' : AnalyticsId,
  'store_id' : StoreId,
});
export const AnalyticsSummary = IDL.Record({
  'total_clicks' : IDL.Nat,
  'total_whatsapp_clicks' : IDL.Nat,
  'daily' : IDL.Vec(Analytics),
});
export const Store = IDL.Record({
  'store_video_url' : IDL.Opt(IDL.Text),
  'created_at' : Timestamp,
  'logo_url' : IDL.Opt(IDL.Text),
  'owner_id' : IDL.Principal,
  'store_name' : IDL.Text,
  'store_slug' : IDL.Text,
  'whatsapp_number' : IDL.Text,
  'enable_video_tour' : IDL.Bool,
  'is_active' : IDL.Bool,
  'status_notes' : IDL.Opt(IDL.Text),
  'store_id' : StoreId,
});
export const StorePublic = IDL.Record({
  'store_video_url' : IDL.Opt(IDL.Text),
  'created_at' : Timestamp,
  'logo_url' : IDL.Opt(IDL.Text),
  'store_name' : IDL.Text,
  'store_slug' : IDL.Text,
  'whatsapp_number' : IDL.Text,
  'enable_video_tour' : IDL.Bool,
  'is_active' : IDL.Bool,
  'status_notes' : IDL.Opt(IDL.Text),
  'store_id' : StoreId,
});
export const SystemMetrics = IDL.Record({
  'total_clicks' : IDL.Nat,
  'active_stores' : IDL.Nat,
  'paused_stores' : IDL.Nat,
});
export const StoreAdminView = IDL.Record({
  'created_at' : Timestamp,
  'owner_id' : IDL.Principal,
  'store_name' : IDL.Text,
  'store_slug' : IDL.Text,
  'is_active' : IDL.Bool,
  'status_notes' : IDL.Opt(IDL.Text),
  'store_id' : StoreId,
});
export const StoreInput = IDL.Record({
  'logo_url' : IDL.Opt(IDL.Text),
  'store_name' : IDL.Text,
  'store_slug' : IDL.Text,
  'whatsapp_number' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getMyStore' : IDL.Func([], [IDL.Opt(Store)], ['query']),
  'getPublicProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getPublicStore' : IDL.Func([IDL.Text], [IDL.Opt(StorePublic)], ['query']),
  'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllStores' : IDL.Func([], [IDL.Vec(StoreAdminView)], ['query']),
  'recordStoreVisit' : IDL.Func([IDL.Text], [], []),
  'recordWhatsappClick' : IDL.Func([IDL.Text], [], []),
  'saveMyStore' : IDL.Func([StoreInput], [Store], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setMyTour' : IDL.Func([IDL.Opt(IDL.Text), IDL.Bool], [Store], []),
  'setProductInStock' : IDL.Func([ProductId, IDL.Bool], [Product], []),
  'setStoreActive' : IDL.Func(
      [StoreId, IDL.Bool, IDL.Opt(IDL.Text)],
      [StoreAdminView],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'image_url' : IDL.Text,
    'product_name' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Text;
  const Timestamp = IDL.Int;
  const StoreId = IDL.Text;
  const Product = IDL.Record({
    'product_id' : ProductId,
    'image_url' : IDL.Text,
    'created_at' : Timestamp,
    'product_name' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'store_id' : StoreId,
    'in_stock' : IDL.Bool,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DateKey = IDL.Text;
  const AnalyticsId = IDL.Text;
  const Analytics = IDL.Record({
    'whatsapp_clicks' : IDL.Nat,
    'click_count' : IDL.Nat,
    'date' : DateKey,
    'analytics_id' : AnalyticsId,
    'store_id' : StoreId,
  });
  const AnalyticsSummary = IDL.Record({
    'total_clicks' : IDL.Nat,
    'total_whatsapp_clicks' : IDL.Nat,
    'daily' : IDL.Vec(Analytics),
  });
  const Store = IDL.Record({
    'store_video_url' : IDL.Opt(IDL.Text),
    'created_at' : Timestamp,
    'logo_url' : IDL.Opt(IDL.Text),
    'owner_id' : IDL.Principal,
    'store_name' : IDL.Text,
    'store_slug' : IDL.Text,
    'whatsapp_number' : IDL.Text,
    'enable_video_tour' : IDL.Bool,
    'is_active' : IDL.Bool,
    'status_notes' : IDL.Opt(IDL.Text),
    'store_id' : StoreId,
  });
  const StorePublic = IDL.Record({
    'store_video_url' : IDL.Opt(IDL.Text),
    'created_at' : Timestamp,
    'logo_url' : IDL.Opt(IDL.Text),
    'store_name' : IDL.Text,
    'store_slug' : IDL.Text,
    'whatsapp_number' : IDL.Text,
    'enable_video_tour' : IDL.Bool,
    'is_active' : IDL.Bool,
    'status_notes' : IDL.Opt(IDL.Text),
    'store_id' : StoreId,
  });
  const SystemMetrics = IDL.Record({
    'total_clicks' : IDL.Nat,
    'active_stores' : IDL.Nat,
    'paused_stores' : IDL.Nat,
  });
  const StoreAdminView = IDL.Record({
    'created_at' : Timestamp,
    'owner_id' : IDL.Principal,
    'store_name' : IDL.Text,
    'store_slug' : IDL.Text,
    'is_active' : IDL.Bool,
    'status_notes' : IDL.Opt(IDL.Text),
    'store_id' : StoreId,
  });
  const StoreInput = IDL.Record({
    'logo_url' : IDL.Opt(IDL.Text),
    'store_name' : IDL.Text,
    'store_slug' : IDL.Text,
    'whatsapp_number' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getMyStore' : IDL.Func([], [IDL.Opt(Store)], ['query']),
    'getPublicProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getPublicStore' : IDL.Func([IDL.Text], [IDL.Opt(StorePublic)], ['query']),
    'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllStores' : IDL.Func([], [IDL.Vec(StoreAdminView)], ['query']),
    'recordStoreVisit' : IDL.Func([IDL.Text], [], []),
    'recordWhatsappClick' : IDL.Func([IDL.Text], [], []),
    'saveMyStore' : IDL.Func([StoreInput], [Store], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setMyTour' : IDL.Func([IDL.Opt(IDL.Text), IDL.Bool], [Store], []),
    'setProductInStock' : IDL.Func([ProductId, IDL.Bool], [Product], []),
    'setStoreActive' : IDL.Func(
        [StoreId, IDL.Bool, IDL.Opt(IDL.Text)],
        [StoreAdminView],
        [],
      ),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };