/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'whatsapp_clicks' : bigint,
  'click_count' : bigint,
  'date' : DateKey,
  'analytics_id' : AnalyticsId,
  'store_id' : StoreId,
}
export type AnalyticsId = string;
export interface AnalyticsSummary {
  'total_clicks' : bigint,
  'total_whatsapp_clicks' : bigint,
  'daily' : Array<Analytics>,
}
export interface Cell { 'value' : Value, 'name' : string }
export type DateKey = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Product {
  'product_id' : ProductId,
  'image_url' : string,
  'created_at' : Timestamp,
  'product_name' : string,
  'category' : string,
  'price' : number,
  'store_id' : StoreId,
  'in_stock' : boolean,
}
export type ProductId = string;
export interface ProductInput {
  'image_url' : string,
  'product_name' : string,
  'category' : string,
  'price' : number,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Store {
  'store_video_url' : [] | [string],
  'created_at' : Timestamp,
  'logo_url' : [] | [string],
  'owner_id' : Principal,
  'store_name' : string,
  'store_slug' : string,
  'whatsapp_number' : string,
  'enable_video_tour' : boolean,
  'is_active' : boolean,
  'status_notes' : [] | [string],
  'store_id' : StoreId,
}
export interface StoreAdminView {
  'created_at' : Timestamp,
  'owner_id' : Principal,
  'store_name' : string,
  'store_slug' : string,
  'is_active' : boolean,
  'status_notes' : [] | [string],
  'store_id' : StoreId,
}
export type StoreId = string;
export interface StoreInput {
  'logo_url' : [] | [string],
  'store_name' : string,
  'store_slug' : string,
  'whatsapp_number' : string,
}
export interface StorePublic {
  'store_video_url' : [] | [string],
  'created_at' : Timestamp,
  'logo_url' : [] | [string],
  'store_name' : string,
  'store_slug' : string,
  'whatsapp_number' : string,
  'enable_video_tour' : boolean,
  'is_active' : boolean,
  'status_notes' : [] | [string],
  'store_id' : StoreId,
}
export interface SystemMetrics {
  'total_clicks' : bigint,
  'active_stores' : bigint,
  'paused_stores' : bigint,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAnalytics' : ActorMethod<[], AnalyticsSummary>,
  'getMyStore' : ActorMethod<[], [] | [Store]>,
  'getPublicProducts' : ActorMethod<[string], Array<Product>>,
  'getPublicStore' : ActorMethod<[string], [] | [StorePublic]>,
  'getSystemMetrics' : ActorMethod<[], SystemMetrics>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllStores' : ActorMethod<[], Array<StoreAdminView>>,
  'recordStoreVisit' : ActorMethod<[string], undefined>,
  'recordWhatsappClick' : ActorMethod<[string], undefined>,
  'saveMyStore' : ActorMethod<[StoreInput], Store>,
  'schema' : ActorMethod<[], string>,
  'setMyTour' : ActorMethod<[[] | [string], boolean], Store>,
  'setProductInStock' : ActorMethod<[ProductId, boolean], Product>,
  'setStoreActive' : ActorMethod<
    [StoreId, boolean, [] | [string]],
    StoreAdminView
  >,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];